apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-operator-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devops-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: devops-operator-controller-manager
    namespace: {{ .Release.Namespace }}